default_platform(:ios)

platform :ios do
  desc "GitHub ActionsからTestFlightへ自動配信する"
  lane :release_to_app_store do
    
    # GitHub Secretsから環境変数を経由してAPIキーを読み込む
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"],
      is_key_content_base64: false
    )

    # CI環境の対話スキップ設定
    setup_ci

    # 先ほどローカルで作った証明書を「読み取り専用」で同期（超安全）
    match(
      type: "appstore", 
      readonly: true,      # クラウド上では書き換えないよう true に戻します
      api_key: api_key,
      app_identifier: "gdisp.indicate.app"
    )

    # クラウド上でのアプリビルド
    build_app(
      workspace: "Gdisp.xcworkspace", 
      scheme: "app2",
      export_method: "app-store",
      xcargs: "CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY='#{ENV["sigh_gdisp.indicate.app_appstore_certificate-name"]}' PROVISIONING_PROFILE_SPECIFIER='#{ENV["sigh_gdisp.indicate.app_appstore_profile-name"]}'"
    )

    # TestFlightへのアップロード
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
